Traceback (most recent call last):
  File "/storage/emulated/0/termux/telegram/leakbase/.py", line 36, in <module>
    client.send_message(CHANNEL, _.text + '

https://leakbase.io' + _.get('href'))
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telethon/client/messages.py", line 823, in send_message
    entity = await self.get_input_entity(entity)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telethon/client/users.py", line 466, in get_input_entity
    raise ValueError(
ValueError: Could not find the input entity for PeerChannel(channel_id=1847528082) (PeerChannel). Please read https://docs.telethon.dev/en/stable/concepts/entities.html to find out more details.